img_size: [3,32,32]
batch_size: 256 
maxlen: 8192
lagevian_steps: 100
lagevian_step_size: 1.0
alpha : 1.0
epochs: 40
learning_rate : 1e-4
objective: cd
cnn_dim : 576
avg_pool_size : 3
in_channels : 3
learning_rate_decay: 1.0
